# Generated by Django 6.1.1 on 2026-09-30 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
